version: "3.9"
services:
  redis:
    image: "redislabs/rejson:latest"
    restart: always
    ports:
      - '6379:6379' 
    command: redis-server --save 120 1 --appendonly yes --loglevel warning --loadmodule /usr/lib/redis/modules/rejson.so
    volumes:
      - redis:/data
  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore 

volumes:
  redis:
    driver: local
  eventstore-volume-data:
    driver: local
  eventstore-volume-logs:
    driver: local
